### ISSUE TITLE
About gpolyencode

### ISSUE THREAD

**Issue by fmaussion** [ryancox/motionless#17]
Hi @ryancox , I have a few questions about gpolyencode, I hope that you can help me out:

Currently, only paths in `DecoratedMaps` can be encoded. Could it be possible to use gpolyencode to also encode a series of markers? I am asking because when I tried to make a map with many markers (e.g. earthquakes during the last 7 days), the url became too long.

The gpolyencode package is old and I'm not sure it is still maintained. It doesn't support python 3. The `gpolyencode.py` module which is located in the examples directory does now work with python 3 (it's just about importing `from six import StringIO`). What do you think about incorporating this piece of code to motionless? It has a non-restrictive license, so all what we have to do is to add their copyright notice to ours. (in fact, it should already be the case since their code is already on our repo)

**Comment by ryancox** [comment]
It sounds like a good idea, but i'm not sure it's possible. Did you read through the docs about markers? https://developers.google.com/maps/documentation/static-maps/intro#Markers

**Comment by fmaussion** [comment]
OK now I've read with more details what polyencode does, this is useless for the markers. The only way to have more markers in that case would be to limit the resolution of their coordinates. It could be added to motionless easily but I don't think it is worth it. What about the other point? I could also try to submit a py3 PR to their gh repo.

**Comment by fmaussion** [comment]
closed via https://github.com/ryancox/motionless/pull/18
