### ISSUE TITLE
Bugfix release

### ISSUE THREAD

**Issue by fmaussion** [ryancox/motionless#21]
Hi @ryancox , you fine with a 1.3.1 release, or would you rather do a 1.4 for consistency ?

**Comment by ryancox** [comment]
1.3.1 is fine

**Comment by fmaussion** [comment]
I justed tagged the version on github, I think you can upload to pypi. Thanks!

**Comment by fmaussion** [comment]
Hi @ryancox , just a short reminder here ;-)

**Comment by ryancox** [comment]
done!

**Comment by fmaussion** [comment]
Great, thanks!
