### ISSUE TITLE
MAX_URL_LEN

### ISSUE THREAD

**Issue by foodlu** [ryancox/motionless#23]
Can you please update  MAX_URL_LEN = 8192. As they have increased allowed size. 
Reference https://developers.google.com/maps/documentation/static-maps/intro#url-size-restriction

**Comment by fmaussion** [comment]
Yes, good idea. Will do this later today

**Comment by foodlu** [comment]
Thank you very much.

Regards,
Vinay Bagul | Co-Founder | Yuñ Solutions

B.Tech M.Tech - Electrical Engineering | IIT Bombay

+91-9096121533

**Comment by fmaussion** [comment]
If you want to get the updated motionless you can install it via the repo with:

``pip install https://github.com/ryancox/motionless.git``

**Comment by foodlu** [comment]
Yeah sure. Thank you..

**Comment by riggsd** [comment]
For those awaiting an official release, version 1.3.1 can be monkey patched like this:

```python
import motionless
motionless.Map.MAX_URL_LEN = 8192
```

**Comment by fmaussion** [comment]
Thanks for the remainder. Indeed we had no further PR than this one, but maybe it is worth a minor release.
