### ISSUE TITLE
Path Simplification for Decorated Map

### ISSUE THREAD

**Issue by riggsd** [ryancox/motionless#26]
GPolyEncode has a built-in path simplification algorithm ([Ramer–Douglas–Peucker](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm)) with configurable distance-based threshold value. That threshold is not currently exposed by the `DecoratedMap()` constructor. Adding this extra parameter is trivial, however...

As far as I can understand this RDP implementation, the `threshold` units are in "degrees". Degrees are not a very intuitive end user unit for an API; meters seems more comprehensible. The default value, `0.00001` corresponds approximately to 1.1 meters at the equator. This simple RDP implementation, operating on lat/lon coordinates in degrees, has the property of operating in the Y (latitude) and X (longitude) dimensions _differently_ as a function of latitude. In other words, allowing the user to express simplification threshold in meters would be an approximation that varies depending on where the path is located latitude-wise.

I can submit a PR which adds `simplification_threshold` as a constructor argument to `DecoratedMap()`. If this is desired, would you prefer that the units for this value be in "degrees" and passed directly to GPolyEncode, or that units be in "approximate meters" and then converted before being passed to GPolyEncode?

(Note that, whether this API change is made or not, motionless _currently_ uses the default value of 0.00001 degrees so that all paths are being simplified at the ~1.1m level.)

**Comment by riggsd** [comment]
Simplification threshold in degrees:
  https://github.com/riggsd/motionless/tree/threshold-degrees

Simplification threshold in meters:
  https://github.com/riggsd/motionless/tree/threshold-meters

**Comment by riggsd** [comment]
Here's an animation showing various simplification thresholds from 0 to 1000 meters:

![simplify_threshold](https://cloud.githubusercontent.com/assets/647785/25057947/8c8cb17a-2129-11e7-9c8f-12742bc1a784.gif)

Threshold of 0 is _no_ simplification of the original path. Note that the above example is at ~36deg latitude.

**Comment by fmaussion** [comment]
Yes please, submit a PR!

I have no strong opinion about it, but I guess you're right that "approximate meters" makes more sense. Ideally, the computations should be done in the local mercator projection of the static map, but I guess this would imply a reprojection into lon/lat for the generation of the url, which is probably undesirable?
