### ISSUE TITLE
Support for Maps API Premium?

### ISSUE THREAD

**Issue by aarongundel** [ryancox/motionless#28]
Are there any plans to add support for gmaps premium here?  Allowable map size for premium is 2048x2048 -- see https://developers.google.com/maps/documentation/static-maps/intro .  Happy to make some pull requests if desired.

**Comment by fmaussion** [comment]
I never used premium before. Is there anything more to do than setting the ``key``, ``size_x`` and ``size_y`` arguments? Because this is already there.

But if something else is needed, PRs are welcome of course!

**Comment by pdr** [comment]
Since the PR was merged for this, this issue might be good to close out?
