### ISSUE TITLE
v1.3.2 release?

### ISSUE THREAD

**Issue by fmaussion** [ryancox/motionless#30]
Hi @ryancox , do you have time this week to push a minor release to pip? If yes let me know, I'll do the tagging/releasing here on github.

**Comment by ryancox** [comment]
sure thing

**Comment by fmaussion** [comment]
OK, sorry it took me so long: https://github.com/ryancox/motionless/releases

Let me know once it's on pypi

**Comment by MaciejM92** [comment]
Hi guys, do you plan to push 1.3.2 to pypi soon? :)

**Comment by fmaussion** [comment]
Thanks for the reminder! Will have a look at some recent PRs in the upcoming days and possibly release a v1.3.3 

I'll let you know here when this happens

**Comment by MaciejM92** [comment]
Thx, btw good job guys!

**Comment by fmaussion** [comment]
@ryancox we had quite a few PRs lately, it would be good to make a new release soon let me know when you are available

**Comment by MaciejM92** [comment]
gentle follow-up :)

**Comment by fmaussion** [comment]
cc @ryancox

**Comment by bartekbrak** [comment]
@ryancox Can we somehow help? :) Not being on PyPI makes caching this package as wheel impossible.

**Comment by ryancox** [comment]
done .. sorry for the delay.. i'll be a better human in the future 😄
