### ISSUE TITLE
generate_url method return character "|" instead of "%7C"

### ISSUE THREAD

**Issue by nibrahimb1993** [ryancox/motionless#39]
Hi Dear Sir/Madam
Thank you for your grate work.
I noticed that after generating url it doesn't convert character "|" to "%7C" so I had to replace it manually.

it's not a big issue but it's good to have in your package.

thank you.

**Comment by fmaussion** [comment]
Thanks a lot for the report! This was corrected in a PR last year: https://github.com/ryancox/motionless/pull/37

To install the latest motionless version, do:

    pip install git+https://github.com/ryancox/motionless.git

Best,

Fabien

**Comment by nibrahimb1993** [comment]
THAT IS GRATE \ (•◡•) /
