### ISSUE TITLE
six dependency imported implicitly in setup.py

### ISSUE THREAD

**Issue by cmcg513** [ryancox/motionless#42]
# Implicit import of six dependency in setup.py causes install failure

Hi there; I encountered an issue installing motionless on a fresh virtualenv for python 3.7.0

Great package by the way! Has been very useful!

## Error message
```
user@localhost:~/some_dir $ pip install motionless
Collecting motionless
  Using cached https://files.pythonhosted.org/packages/.../motionless-1.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/.../motionless/setup.py", line 3, in <module>
        from motionless import __version__
      File "/.../motionless/motionless.py", line 2, in <module>
        from six.moves.urllib.parse import quote, urlparse
    ModuleNotFoundError: No module named 'six'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /.../motionless/
```

## Cause

The [setup.py](https://github.com/ryancox/motionless/blob/master/setup.py) script imports the version from [motionless.py](https://github.com/ryancox/motionless/blob/master/motionless.py) at [line #3](https://github.com/ryancox/motionless/blob/master/setup.py#L3).

This import implicitly invokes the import of the six module in [motionless.py](https://github.com/ryancox/motionless/blob/master/motionless.py) at [line #5](https://github.com/ryancox/motionless/blob/master/motionless.py#L5). 

If six is not yet installed, installing via setuptools/pip will fail

## Fix

Maybe move the version out into its own file?

**Comment by fmaussion** [comment]
Thanks for the report!

I agree that the error message is not great, but six is a hard requirement of motionless so users have to install it anyway. 

I'm happy to take a fix for this: it'll imply removing any reference to six before it is intalled by pip.

**Comment by chingc** [comment]
I ran into this issue today even though I have `six` explicitly in my `requirements.txt`.  It forces me to `pip install six` ahead of time which is not great.  :(

**Comment by chingc** [comment]
Is this being worked on?  Motionless should automatically install six as a dependency and not expect it to already be on the user's system.

**Comment by fmaussion** [comment]
A fix is welcome!

**Comment by JMSwag** [comment]
@fmaussion Done -> #43
