### ISSUE TITLE
PyPI package out of date

### ISSUE THREAD

**Issue by chingc** [ryancox/motionless#44]
The PyPI package is still 1.3.2.

**Comment by fmaussion** [comment]
Yes I'm sorry but I don't have the pypi credentials and the original author @ryancox is quite hard to get to. 

In the meantime, you should install from github master...

**Comment by raybellwaves** [comment]
This would be nice to have. I'm working on https://github.com/conda-forge/staged-recipes/pull/13309
Ping @ryancox

**Comment by fmaussion** [comment]
I have commit rights on this repo but not on PyPi - I don't know if there is something we can do to get credentials there.

**Comment by raybellwaves** [comment]
If the license permits could work out of a new package "motionless2"? With all credit going to the development of motionless of course.

**Comment by fmaussion** [comment]
It would really be a shame... I'll try to write to @ryancox on hie email.

**Comment by fmaussion** [comment]
Sorry it took a while but I have credentials now and can push to pypi: https://pypi.org/project/motionless/ 

@raybellwaves , care to start a conda-forge recipe?

**Comment by chingc** [comment]
Thanks for updating PyPI!
