### ISSUE TITLE
there is no installation instructions in the readme

### ISSUE THREAD

**Issue by mnky9800n** [ryancox/motionless#48]
This would help new users who have never heard of motionless before today. It seems like it is available in the oggm channel which is a non-standard channel so it would not be obvious to new users:

https://anaconda.org/oggm/motionless

However, it may be that you only plan to have the package installed with other oggm modules and thus it should only be installed via oggm-dep. But this is not at all clear from the readme so the readme should be updated to reflect this.

**Comment by fmaussion** [comment]
see https://github.com/ryancox/motionless/issues/44 -> I'll update the install instructions once the conda recipe is up

**Comment by fmaussion** [comment]
Closed via https://github.com/ryancox/motionless/commit/5213a3e308aba217497935161249f46a1b40d1c1
