### ISSUE TITLE
Google static map API marker colors

### ISSUE THREAD

**Issue by mocharlaaditi** [ryancox/motionless#51]
According to the google static maps API documentation it looks like the marker color also takes in a 16 bit hex value
<img width="924" alt="Image 2022-03-03 at 5 23 06 PM" src="https://user-images.githubusercontent.com/70959372/156670830-7a684535-6df1-4f9c-83b3-3260a89e7768.png">

Is there a reason to limit the marker colors to only the color list?

**Comment by fmaussion** [comment]
Markers should accept such colors already?

https://github.com/ryancox/motionless/blob/2fa3e66b8c32008af9e771dd2b1b596a0154fbef/motionless/__init__.py#L44-L81

If there is a bug, can you please show a minimal working example of the bug?

**Comment by mocharlaaditi** [comment]
I was passing in capital X instead of lowercase. Thanks!
